"""
Optional reverse proxy.

For any service with `route.host`, perch can generate a Caddyfile and run
Caddy on the project network. Caddy gives you automatic HTTPS for real domains
(and works fine on *.localhost for local dev), proxying each hostname to its
container. This is the "expose my webapp on a URL" half of hosting.
"""

from __future__ import annotations

from .manifest import Manifest


def caddyfile(manifest: Manifest) -> str:
    project = manifest.project
    blocks: list[str] = []
    for svc in manifest.services:
        if not svc.route.host or not svc.port:
            continue
        upstream = f"perch-{project}-{svc.name}:{svc.port}"
        path = svc.route.path or ""
        if path:
            body = f"\thandle_path {path}* {{\n\t\treverse_proxy {upstream}\n\t}}"
        else:
            body = f"\treverse_proxy {upstream}"
        blocks.append(f"{svc.route.host} {{\n{body}\n}}")
    header = "# Generated by perch. Do not edit by hand; edit perch.yaml.\n"
    return header + "\n\n".join(blocks) + "\n"


def has_routes(manifest: Manifest) -> bool:
    return any(s.route.host and s.port for s in manifest.services)
