"""
Optional reverse proxy.

For any service with `route.host`, perch can generate a Caddyfile and run
Caddy on the project network. Caddy gives you automatic HTTPS for real domains
(and works fine on *.localhost for local dev), proxying each hostname to its
container. This is the "expose my webapp on a URL" half of hosting.
"""

from __future__ import annotations

from .manifest import Manifest


def caddyfile(manifest: Manifest, shares: "dict | None" = None) -> str:
    """`shares` maps service name -> host port for `perch share`: hostname routing
    (route.host) only resolves on the developer's machine, so shared services get a
    port-based site block a teammate can reach as http://<LAN-IP>:<port> with no
    DNS, hosts-file, or certificate setup."""
    project = manifest.project
    by_name = manifest.by_name()
    blocks: list[str] = []
    for svc in manifest.services:
        if not svc.route.host or not svc.port:
            continue
        upstream = f"perch-{project}-{svc.name}:{svc.port}"
        path = svc.route.path or ""
        if path:
            body = f"\thandle_path {path}* {{\n\t\treverse_proxy {upstream}\n\t}}"
        else:
            body = f"\treverse_proxy {upstream}"
        blocks.append(f"{svc.route.host} {{\n{body}\n}}")
    for name, entry in sorted((shares or {}).items()):
        # accept both share shapes: bare port (v1 state) or {port, https}
        port = entry.get("port") if isinstance(entry, dict) else entry
        https = bool(entry.get("https")) if isinstance(entry, dict) else False
        svc = by_name.get(name)
        if svc is None or not svc.port or not isinstance(port, int):
            continue
        upstream = f"perch-{project}-{name}:{svc.port}"
        if https:
            # Caddy's internal CA: real TLS on the intranet with no public domain.
            # Browsers warn until teammates trust the root cert once (docs walk it).
            blocks.append(f"https://:{port} {{\n\ttls internal\n"
                          f"\treverse_proxy {upstream}\n}}")
        else:
            blocks.append(f"http://:{port} {{\n\treverse_proxy {upstream}\n}}")
    header = "# Generated by perch. Do not edit by hand; edit perch.yaml.\n"
    return header + "\n\n".join(blocks) + "\n"


def has_routes(manifest: Manifest) -> bool:
    return any(s.route.host and s.port for s in manifest.services)
